<Button>:
    text: "TÍNH TOÁN"
    label: "tinhtoan"
    size_hint: (1, 1)
    pos_hint: {'center_x': 0.5, 'center_y': .1}
    background_color: 0.1, 0.5, 0.6, 1
    on_press: app.on_press_button(self)
<BoxLayout>:
    canvas:
        Rectangle:
            source: 'Heading2.png'
            size: self.size
            pos: self.pos
<Label>:
    text_size: self.size
    halign: 'center'
    valign: 'center'
