<Button>:
    text: "TÍNH TOÁN"
    label: "tinhtoan"
    source: 'Heading.png'
    size_hint: (1, 1)
    pos_hint: {'center_x': 0.5, 'center_y': .1}
    background_color: 1, 1, 6, 2
    on_press: app.on_press_button(self)
<BoxLayout>:
    canvas:
        Rectangle:
            source: 'Heading2.png'
            size: self.size
            pos: self.pos
<Label>:
    text_size: self.size
    halign: 'center'
    valign: 'center'
    color : "blue"
    source: 'Heading2.png'